[package]
name = "letsdyor"
version = "1.0.0"
authors = []

[addresses]
owner = "5d49fe998ce0f9969d4ccbf67e7496c2a5d5f3826296d56673246f43c817b56a"
letsdyor = "72aba4bdb1e35e08a8335002ff708105aaa0acb2aa461d962c6170aaa5115797"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
