[package]
name = "letsdyor"
version = "1.0.0"
authors = []

[addresses]
owner = "5d49fe998ce0f9969d4ccbf67e7496c2a5d5f3826296d56673246f43c817b56a"
letsdyor = "17b0b02730e279de1929daf21beafeadc164ac5d844699c04e0fafb2b5026084"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
