[package]
name = "letsdyor"
version = "1.0.0"
authors = []

[addresses]
owner = "5d49fe998ce0f9969d4ccbf67e7496c2a5d5f3826296d56673246f43c817b56a"
letsdyor = "f0079fb1bd2bc0b07fd79338be86d9a89d87c9a7ba0f4960f544c481910a8d4d"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
